# Generated by Django 2.0.6 on 2018-06-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet_sites', '0004_auto_20180602_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_value', models.CharField(max_length=500, verbose_name='Значение')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='cabinet_sites.Site', verbose_name='Сайт')),
            ],
        ),
    ]
