# Generated by Django 2.0.6 on 2018-06-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_contentkeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentkey',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentkeys', to='cabinet_sites.Site', verbose_name='Сайт'),
        ),
    ]
