# Generated by Django 2.0.6 on 2018-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_contentkeys', '0002_auto_20180602_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentkey',
            name='conversions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentkey',
            name='pageviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentkey',
            name='unique_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
