# Generated by Django 2.0.6 on 2018-06-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
