# Generated by Django 2.0.6 on 2018-06-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_sites', '0002_auto_20180601_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(max_length=500, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
