# Generated by Django 2.0.6 on 2018-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_sites', '0003_auto_20180601_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='domain',
        ),
        migrations.AddField(
            model_name='site',
            name='page_url',
            field=models.CharField(default=1, max_length=500, verbose_name='URL страницы'),
            preserve_default=False,
        ),
    ]
