# Generated by Django 2.0.6 on 2018-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('request_get', models.TextField()),
                ('request_post', models.TextField()),
                ('request_files', models.TextField()),
                ('request_cookies', models.TextField()),
                ('request_meta', models.TextField()),
            ],
        ),
    ]
