# Generated by Django 2.0.6 on 2018-06-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerlogentry',
            name='cookie_mark',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trackerlogentry',
            name='ip',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trackerlogentry',
            name='useragent',
            field=models.CharField(default='', max_length=500),
        ),
    ]
