# Generated by Django 2.0.6 on 2018-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180609_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerlogentry',
            name='request_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trackerlogentry',
            name='request_cookies',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trackerlogentry',
            name='request_files',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trackerlogentry',
            name='request_get',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trackerlogentry',
            name='request_meta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trackerlogentry',
            name='request_post',
            field=models.TextField(default=''),
        ),
    ]
