# Generated by Django 2.0.6 on 2018-06-01 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='selector',
            field=models.CharField(max_length=500, verbose_name='Селектор'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='cabinet_sites.Site', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
