# Generated by Django 2.0.6 on 2018-06-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_contentkeys', '0002_auto_20180602_1418'),
        ('cabinet_tags', '0002_auto_20180601_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Содержимое')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contentkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_values', to='cabinet_contentkeys.ContentKey', verbose_name='Контент-ключ')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_values', to='cabinet_tags.Tag', verbose_name='Блок')),
            ],
        ),
    ]
